### ISSUE TITLE
Test media doesn't play

### ISSUE THREAD

**Issue by Consti10** [egnor/pivid#9]
Hello,

I cannot play most of the test media files. I get errors like this:
`openhd@raspberrypi:~/pivid $ ./build/pivid_play --media test_media/kitten.rgba.png 
=== Video drivers ===
=> /dev/dri/card1 (vc4): platform/gpu/drm/card1 (gpu)

11:49:15.092     23u I [display] Opening display "/dev/dri/card1"...
11:49:15.152  60244u I [pivid_play] Start: 2022-08-28 11:49:15.153Z
11:49:15.180     18u I [player] s32 Launching frame player...
11:49:15.184   3250u E [libav] png[0xb5801e80] Invalid PNG signature 0x76657273696F6E20.
11:49:15.184      6u E [libav] png[0x2e000e0] Invalid PNG signature 0x76657273696F6E20.
11:49:15.184    105u I [libav] image2[0xb5800800] decoding for stream 0 failed
11:49:15.184     54u I [libav] image2[0x2dfea70] decoding for stream 0 failed
11:49:15.184     96u W [libav] image2[0xb5800800] Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
11:49:15.184     29u W [libav] image2[0x2dfea70] Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Segmentation fault
`
If I downlad the BigBuckBunny from hello_drmprime, it works.

**Comment by egnor** [comment]
The media directory uses `git-lfs`, do you have that installed? If not,
you'll just get teeny text files for all the media files.

**Comment by egnor** [comment]
Looking more at this, I do think lack of `git-lfs` is your issue. I should maybe edit the README to make that more prominent as a dependency? Reopen this issue as needed if that's not your problem!

**Comment by Consti10** [comment]
I can confirm the issue was git-lfs.
I had to install git-lfs, then clone the repo again. Now the test videos / scripts work without issues.
Btw, cngratulations, this is the first project for the rpi I found that does multiple planes, including video, using drm/kms.
Must have been a hell to debug.
